name: keyshare CD to Heroku

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  buildReactAssets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
      - name: install npm dependencies
        run: (cd ./frontend && npm install)
      - name: generate static assets
        run: (cd ./frontend && npm run build)

  buildServerJar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: build with Gradle
        run: ./gradlew build jar #TODO: move jar

  deployToHeroku:
    runs-on: ubuntu-latest

    needs: [buildReactAssets, buildServerJar]

    steps:
      - uses: actions/checkout@v2
      - name: Commit on the runner
        run: 
          git config user.email "runner@github.com";
          # git config user.name "Runner";
          # git add -f
          # git add -f
          # git commit -m "None"
      - name: Deploy to Heroku
        run: git checkout `git subtree split -P iterations`; git push -f origin HEAD:heroku-deploy
