name: keyshare CD to Heroku

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  buildReactAssets:
    runs-on: ubuntu-latest

    steps:
      - name: init repo
        run: /usr/bin/git init /home/runner/work/Keyshare/Keyshare
      - name: add remote
        run: /usr/bin/git remote add origin https://github.com/shintyl/Keyshare
      - name: fetch
        run: git fetch
      - name: checkout from dev-deploy
        run: git checkout dev-deploy
      - name: force push to main-deploy
        run:
          git config user.email "runner@github.com";
          git config user.name "Runner";
          git push -f origin HEAD:main-deploy
