name: keyshare CD to Heroku

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  buildReactAssets:
    runs-on: ubuntu-latest

    steps:
      - name: checkout from dev-deploy
        run: git checkout dev-deploy
      - name: force push to main-deploy
        run: git push -f origin HEAD:main-deploy
