name: keyshare CD to Heroku

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  buildReactAssets:
    runs-on: ubuntu-latest

    steps:
      - name: init repo
        run: /usr/bin/git init /home/runner/work/Keyshare/Keyshare; /usr/bin/git remote add origin https://github.com/shintyl/Keyshare
      - name: checkout from dev-deploy
        run: git checkout dev-deploy
      - name: force push to main-deploy
        run: git push -f origin HEAD:main-deploy
